version: '3.5'
networks:
  default: 
    external:
       name: ${NETWORK}
services:
  app:
     image: joshava/cloudflare-ddns
     container_name: ${LABEL}
     restart: unless-stopped
     volumes:
       - ./config/config.yaml:/app/config.yaml
     environment:
       - PUID=$PUID
       - PGID=$PGID
       - TZ=$TZ




