---
version: '3.5'
networks:
  default: 
    external:
      name: ${NETWORK}
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: ${LABEL}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - .config:/config
      - /mnt/media/_down:/data
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - GUID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
    #  - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
    #  - "traefik.http.routers.${LABEL}-rtr.tls=true"
    #  - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
    #  - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to use .htpasswd login
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
      # uncomment to use authelia
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
      # uncomment to restrict traefik to localnetwork
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"




