---
networks:
  default:
    external: true
    name: ${NETWORK}
services:
  authelia:
     image: authelia/authelia:4.38
     container_name: ${LABEL}
     restart: unless-stopped
     volumes:
       - ./config:/config
     environment:
       - TZ=${TZ}
       - PUID=${PUID}
       - PGID=${PGID}
       - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
       - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
       - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
     #  - AUTHELIA_DUO_API_INTEGRATION_KEY_FILE=/run/secrets/authelia_duo_api_integration_key
     #  - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
     secrets:
       - authelia_jwt_secret
       - authelia_session_secret
       - authelia_storage_encryption_key
      # - authelia_duo_secret
     expose:
       - 9091
#     ports:
#       - 9091:9091
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.${LABEL}-rtr.entrypoints=websecure"
       - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
       - "traefik.http.routers.${LABEL}-rtr.tls=true"
       - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
       - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
       #middlewares
       #uncomment below to disable login
       #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
       - "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
       #uncomment to restrict traefik to localnetwork
       #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
       #uncomment to autoupdate
       #- "com.centurylinklabs.watchtower.enable=true"

secrets:
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key
