---
networks:
  default:
    name: ${NETWORK}
    external: true
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: ${LABEL}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
      - ./books/metadata.db:/books/metadata.db:rw
      - /mnt/media/media/calibre:/books
    ports:
      - 8083:8083
    environment:
      - PUID=${PUID}
      - GUID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
    #  - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
    #  - "traefik.http.routers.${LABEL}-rtr.tls=true"
    #  - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
    #  - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to use .htpasswd login
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
      # uncomment to use authelia
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
      # uncomment to restrict traefik to localnetwork
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"




