---
networks:
  default: 
    name: ${NETWORK}
    external: true
services:
  pihole:
    image: pihole/pihole:latest
    container_name: ${LABEL}
    restart: unless-stopped
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_UID=${PUID}
      - PIHOLE_GID=${PGID}
    #cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
    #  - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
    #  - "traefik.http.routers.${LABEL}-rtr.tls=true"
    #  - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
    #  - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to use .htpasswd login
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
      # uncomment to use authelia
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
      # uncomment to restrict traefik to localnetwork
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"




