version: '3.5'

networks:
  default: 
    external:
      name: ${NETWORK}

services:
  nextcloud_app:
    image: nextcloud
    container_name: nextcloud
    depends_on: 
      - nextcloud_db
    volumes:
      - /mnt/media/docker/nextcloud/data:/var/www/html
      - /etc/localtime:/etc/localtime.ro
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_HOSTNAME=${NEXTCLOUD_HOSTNAME}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextcloud_db:3306
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
      - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
      - "traefik.http.routers.${LABEL}-rtr.tls=true"
      - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
      - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"

  nextcloud_db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
        
