---
networks:
  default: 
    name: ${NETWORK}
    external: true
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: ${LABEL}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./data:/config
      - /mnt/media/_down:/data
     
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - GUID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - COMPOSE_HTTP_TIMEOUT=120
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
    #  - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
    #  - "traefik.http.routers.${LABEL}-rtr.tls=true"
    #  - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
    #  - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to use .htpasswd login
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
      # uncomment to use authelia
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
      # uncomment to restrict traefik to localnetwork
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"




