services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - ${NETWORK}
      - socket_proxy
    ports:
     - "3000:3000"
    volumes:
      - ./data/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.${LABEL}-rtr.entrypoints=websecure"
      - "traefik.http.routers.${LABEL}-rtr.rule=Host(`$DOMAINNAME`) || Host(`www.$DOMAINNAME_1`)" # Both domain.com and www.domain.com
      # Middlewares
      - "traefik.http.routers.${LABEL}-rtr.middlewares=chain-basic-auth@file"
      # HTTP Services
      - "traefik.http.routers.${LABEL}-rtr.service=homepage-svc"
      - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
