---
version: '3.5'
networks:
  default: 
    external:
      name: ${NETWORK}
services:
  app_openhab:
    image: openhab/openhab:latest
    container_name: ${LABEL}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab_addons:/openhab/addons
      - ./openhab_conf:/openhab/conf
      - ./openhab_userdata:/openhab/userdata
    ports:
      - target: 8080
        published: 8306
        protocol: tcp
        mode: host
    command: "tini -s ./start.sh server"
#    environment:
#      - OPENHAB_HTTP_PORT=8080
#      - OPENHAB_HTTPS_PORT=8443
#      - EXTRA_JAVA_OPTS=-Duser.timezone=${TZ}
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
#      - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
#      - "traefik.http.routers.${LABEL}-rtr.tls=true"
#      - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
#      - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to use .htpasswd login
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
      # uncomment to use authelia
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
      # uncomment to restrict traefik to localnetwork
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"




