---
version: '3.5'
networks:
  default: 
    external:
      name: ${NETWORK}
services:
  app:
    image: nginx
    container_name: ${LABEL}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - NGINX_HOST=${CNAME}.${DOMAINNAME}
      - NGINX_PORT=${INTERNALPORT}
    volumes:
      - ./html:/usr/share/nginx/html:ro 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
      - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.${DOMAINNAME}`)"
      - "traefik.http.routers.${LABEL}-rtr.tls=true"
      - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
      - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
      # uncomment to use .htpasswd login
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=middlewares-basic-auth@file"
      # uncomment to use authelia
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=chain-authelia@file"
      # uncomment to restrict traefik to localnetwork
      #- "traefik.http.routers.${LABEL}-rtr.middlewares=onlyLocalNetwork@file"
      # uncomment to autoupdate
      #- "com.centurylinklabs.watchtower.enable=true"




