---
networks:
  default:
    name: ${NETWORK}
    external: true

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: ${LABEL}
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
