services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #user: 1000:1000
    #devices:
    #  - /dev/dri:/dev/dri # for harware transcoding
    ports:
      - "8096:8096"
      # - "8920:8920" # Emby also uses same port if running both
    environment:
      UMASK_SET: 022
      TZ: $TZ
    volumes:
      - ./appdata/jellyfin:/config:rw
      - ./cache:/cache:rw
      - /mnt/media/_down:/data/media:rw
      - ./downloads:/data/downloads
      #- /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
