---
networks:
  default:
    external: true
    name: ${NETWORK}

services:
  minio:
    container_name: ${LABEL}
    #image: "dimianstudio/minio-arm" #for raspberry
    image: minio/minio
    restart: unless-stopped
#    ports:
#      - "9000:9000"
    security_opt:
      - no-new-privileges:true
    volumes:
       - /mnt/media/docker/minio:/export
       - ./minio_config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
      MINIO_DOMAIN: $MINIO_DOMAIN
    #  MINIO_HTTP_TRACE: /tmp/minio.log
    command: server /export
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${LABEL}-rtr.entrypoints=https"
      - "traefik.http.routers.${LABEL}-rtr.rule=Host(`${CNAME}.$DOMAINNAME`)"
      - "traefik.http.routers.${LABEL}-rtr.tls=true"
      - "traefik.http.routers.${LABEL}-rtr.service=${LABEL}-svc"
      - "traefik.http.services.${LABEL}-svc.loadbalancer.server.port=${INTERNALPORT}"
