networks:
  default:
    name: ${NETWORK}
    external: true
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influxdb_user
      DOCKER_INFLUXDB_INIT_PASSWORD: influxdb_password
      DOCKER_INFLUXDB_INIT_ORG: homelab
      DOCKER_INFLUXDB_INIT_BUCKET: proxmox
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
